# Generated by Django 2.1.7 on 2019-02-16 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AGAMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('aga_id', models.PositiveIntegerField()),
                ('chapter', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('rating', models.FloatField()),
                ('sigma', models.FloatField()),
                ('expiry', models.DateField()),
                ('updated', models.DateField()),
                ('mtype', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'aga_members',
            },
        ),
    ]
